# Generated by Django 3.2 on 2021-05-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210524_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ID_card',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='address',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='fax',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='flag',
            field=models.CharField(choices=[('0', '已注销'), ('1', '正常')], default='正常', max_length=32),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='mobile',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='region',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='right',
            field=models.CharField(choices=[('common', '普通用户'), ('vip', 'vip用户')], default='普通用户', max_length=32),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='zip',
            field=models.IntegerField(blank=True, default=100000),
        ),
    ]
