# Generated by Django 3.2 on 2021-05-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=32)),
                ('topic', models.TextField()),
                ('src', models.CharField(max_length=100)),
            ],
        ),
    ]
