# Generated by Django 3.2 on 2021-05-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='type',
            field=models.CharField(choices=[('.pdf', 'pdf'), ('.docx', 'word')], default='.docx', max_length=10),
        ),
    ]
