# Generated by Django 3.2 on 2021-05-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0002_fileinfo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='file_id',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
