# Generated by Django 3.2 on 2021-06-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0003_alter_fileinfo_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='file',
            field=models.FileField(default=None, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='prices',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='publish_state',
            field=models.CharField(choices=[('private', '未公开'), ('public', '已公开')], default='未公开', max_length=10),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='uploader',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
