# Generated by Django 3.2 on 2021-06-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0004_auto_20210606_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='uploader',
            field=models.CharField(max_length=32),
        ),
    ]
